import React, { useEffect, useRef, useState } from "react";
import { api } from "./api";

const avatarPalette = [["#6d5dfc", "#22d3ee"], ["#f97316", "#ec4899"], ["#10b981", "#3b82f6"], ["#eab308", "#8b5cf6"], ["#ef4444", "#06b6d4"]];

function Avatar({ username = "U", large = false }) {
  const code = username.split("").reduce((sum, ch) => sum + ch.charCodeAt(0), 0);
  const pair = avatarPalette[code % avatarPalette.length];
  return <div className={`avatar ${large ? "avatar-lg" : ""}`} style={{ "--avatar-a": pair[0], "--avatar-b": pair[1] }}>{username.slice(0, 2).toUpperCase()}</div>;
}
function formatDate(date) {
  const d = new Date(date), diff = Math.max(0, Date.now() - d.getTime()), m = Math.floor(diff / 60000);
  if (m < 1) return "just now"; if (m < 60) return `${m}m`; const h = Math.floor(m / 60); if (h < 24) return `${h}h`; const days = Math.floor(h / 24); if (days < 7) return `${days}d`; return d.toLocaleDateString(undefined, { day: "numeric", month: "short" });
}

function AuthScreen({ onAuth }) {
  const [mode, setMode] = useState("login"), [form, setForm] = useState({ name: "", username: "", email: "", password: "" }), [loading, setLoading] = useState(false), [error, setError] = useState("");
  const update = k => e => setForm({ ...form, [k]: e.target.value });
  async function submit(e) { e.preventDefault(); setError(""); setLoading(true); try { const result = mode === "login" ? await api.login({ email: form.email, password: form.password }) : await api.signup(form); localStorage.setItem("neural_token", result.token); onAuth(result.user); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <div className="auth-page"><div className="auth-glow glow-one"/><div className="auth-glow glow-two"/><div className="auth-card auth-card-pro">
    <div className="brand brand-center"><div className="brand-mark">N</div><div><div className="brand-name">Neural Social</div><div className="brand-sub">A smarter community space</div></div></div>
    <div className="auth-heading"><span className="eyebrow">FULL STACK SOCIAL PLATFORM</span><h1>{mode === "login" ? "Welcome back 👋" : "Create your account"}</h1><p>{mode === "login" ? "Pick up the conversation where you left off." : "Create your identity and start sharing with the community."}</p></div>
    {error && <div className="alert error">⚠ {error}</div>}
    <form onSubmit={submit} className="auth-form">{mode === "signup" && <><label>Full name<input value={form.name} onChange={update("name")} placeholder="Your full name" maxLength={40} required /></label><label>Username<input value={form.username} onChange={update("username")} placeholder="yourusername" maxLength={24} required /></label></>}<label>Email<input type="email" value={form.email} onChange={update("email")} placeholder="you@example.com" required /></label><label>Password<input type="password" value={form.password} onChange={update("password")} placeholder="Minimum 6 characters" minLength={6} required /></label><button className="primary-btn full auth-submit" disabled={loading}>{loading ? <span className="spinner"/> : mode === "login" ? "Enter Neural Social →" : "Create Account →"}</button></form>
    <div className="auth-switch">{mode === "login" ? "New here?" : "Already have an account?"}<button onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); }}>{mode === "login" ? "Create account" : "Login"}</button></div><div className="demo-note">Internship Round 1 • MERN-style social application</div>
  </div></div>;
}

function Composer({ user, onCreated }) {
  const [text, setText] = useState(""), [image, setImage] = useState(""), [imageName, setImageName] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const fileRef = useRef(null);
  function handleImage(e) { const file = e.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) return setError("Please choose an image file."); if (file.size > 2 * 1024 * 1024) return setError("Please choose an image below 2MB."); setError(""); setImageName(file.name); const reader = new FileReader(); reader.onload = () => { const img = new Image(); img.onload = () => { const max = 1200, scale = Math.min(1, max / Math.max(img.width, img.height)), canvas = document.createElement("canvas"); canvas.width = Math.round(img.width * scale); canvas.height = Math.round(img.height * scale); canvas.getContext("2d").drawImage(img, 0, 0, canvas.width, canvas.height); setImage(canvas.toDataURL("image/jpeg", .78)); }; img.src = reader.result; }; reader.readAsDataURL(file); }
  async function submit(e) { e.preventDefault(); if (!text.trim() && !image) return setError("Write something or add an image."); setBusy(true); setError(""); try { const result = await api.createPost({ text, image }); setText(""); setImage(""); setImageName(""); if (fileRef.current) fileRef.current.value = ""; onCreated(result.post); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="composer card"><div className="section-label"><span className="pulse-dot"/> Create something new</div><div className="composer-row"><Avatar username={user.username} large/><div className="composer-main"><textarea value={text} onChange={e => setText(e.target.value)} maxLength={2000} placeholder="What is on your mind today?"/>{image && <div className="image-preview"><img src={image} alt="Selected preview"/><button type="button" className="remove-image" onClick={() => { setImage(""); setImageName(""); fileRef.current.value = ""; }}>×</button></div>}{error && <div className="inline-error">{error}</div>}<div className="composer-actions"><input ref={fileRef} type="file" accept="image/*" hidden onChange={handleImage}/><button type="button" className="attach-btn" onClick={() => fileRef.current?.click()}>▧ Photo {imageName && <small>{imageName}</small>}</button><span className="char-count">{text.length}/2000</span><button className="primary-btn post-btn" disabled={busy}>{busy ? <span className="spinner"/> : "Publish"}</button></div></div></div></form>;
}

function PostCard({ post, onLike, onComment, onDelete }) {
  const [commentText, setCommentText] = useState(""), [showComments, setShowComments] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submitComment(e) { e.preventDefault(); if (!commentText.trim()) return; setBusy(true); try { await onComment(post._id, commentText.trim()); setCommentText(""); setShowComments(true); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <article className="post-card card"><div className="post-header"><Avatar username={post.author.username} large/><div className="post-author"><strong>{post.author.name}</strong><span>@{post.author.username} · {formatDate(post.createdAt)}</span></div>{post.isOwner && <button className="more-btn" onClick={() => onDelete(post._id)}>•••</button>}</div>{post.text && <p className="post-text">{post.text}</p>}{post.image && <div className="post-image-wrap"><img src={post.image} alt={`Post by ${post.author.username}`} className="post-image"/></div>}<div className="engagement"><button className={`engage-btn ${post.likedByMe ? "liked" : ""}`} onClick={() => onLike(post._id)}><span>{post.likedByMe ? "♥" : "♡"}</span>{post.likeCount} Likes</button><button className="engage-btn" onClick={() => setShowComments(!showComments)}><span>◯</span>{post.commentCount} Comments</button></div>{showComments && <div className="comments"><div className="comment-list">{post.comments?.length ? post.comments.map(c => <div className="comment" key={c._id}><Avatar username={c.username}/><div className="comment-body"><div><strong>@{c.username}</strong><span>{formatDate(c.createdAt)}</span></div><p>{c.text}</p></div></div>) : <div className="no-comments">No comments yet. Start the conversation.</div>}</div>{error && <div className="inline-error">{error}</div>}<form className="comment-form" onSubmit={submitComment}><input value={commentText} onChange={e => setCommentText(e.target.value)} maxLength={300} placeholder="Write a comment..."/><button className="comment-send" disabled={busy || !commentText.trim()}>Send</button></form></div>}</article>;
}

function Empty({ icon = "✦", title, text }) { return <div className="card empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>; }

function Nav({ page, setPage, user, logout }) {
  const items = [["home", "⌂", "Home"], ["explore", "⌕", "Explore"], ["create", "+", "Create"], ["notifications", "◉", "Notifications"], ["profile", "◎", "Profile"]];
  return <><header className="topbar"><div className="topbar-inner"><button className="brand brand-button" onClick={() => setPage("home")}><div className="brand-mark">N</div><div><div className="brand-name">Neural Social</div><div className="brand-sub">Connect. Share. Grow.</div></div></button><div className="topbar-search"><span>⌕</span><input value={page === "explore" ? "" : undefined} onChange={() => {}} onFocus={() => setPage("explore")} placeholder="Search the community..." readOnly/></div><div className="top-actions"><div className="online-pill"><span/> Online</div><button className="avatar-button" onClick={() => setPage("profile")}><Avatar username={user.username}/></button></div></div></header><nav className="mobile-nav">{items.map(([id, icon, label]) => <button key={id} className={page === id ? "active" : ""} onClick={() => setPage(id)}><span>{icon}</span>{label}</button>)}</nav></>;
}
function Sidebar({ page, setPage, user, logout }) { const items = [["home", "⌂", "Home", ""], ["explore", "⌕", "Explore", ""], ["create", "+", "Create post", "NEW"], ["notifications", "◉", "Notifications", "2"], ["profile", "◎", "My profile", ""]]; return <aside className="sidebar"><div className="profile-card card"><div className="cover"/><div className="profile-content"><Avatar username={user.username} large/><h3>{user.name}</h3><p>@{user.username}</p><div className="profile-stats"><span><b>Social</b><small>Community</small></span><span><b>∞</b><small>Connections</small></span></div></div></div><div className="side-nav card">{items.map(([id, icon, label, badge]) => <button key={id} className={`side-link ${page === id ? "active" : ""}`} onClick={() => setPage(id)}><span className="side-icon">{icon}</span>{label}{badge && <b>{badge}</b>}</button>)}<div className="nav-divider"/><button className="side-link logout-link" onClick={logout}><span className="side-icon">↪</span>Log out</button></div><div className="tip-card card"><span className="tip-icon">✦</span><div><strong>Build your network</strong><p>Share ideas, images and useful updates with your community.</p></div></div></aside>; }

function HomePage({ user, posts, pagination, pageNo, loading, error, setError, addPost, likePost, commentPost, deletePost, loadPosts, setPage }) { return <section className="page-content"><div className="hero-card"><div><span className="eyebrow">YOUR COMMUNITY, YOUR SPACE</span><h1>Good to see you, {user.name.split(" ")[0]}.</h1><p>Share ideas, discover conversations and keep your community moving.</p><div className="hero-actions"><button className="primary-btn" onClick={() => setPage("create")}>Create a post <span>↗</span></button><button className="ghost-btn" onClick={() => setPage("explore")}>Explore community</button></div></div><div className="hero-orb">✦</div></div><div className="page-title"><div><span className="eyebrow">LIVE FEED</span><h2>Latest from the community</h2><p>Fresh posts from everyone on Neural Social.</p></div><span className="live-badge">● LIVE</span></div>{error && <div className="alert error">{error}</div>}<div className="posts">{loading && posts.length === 0 ? <Empty icon="◌" title="Loading your feed" text="Fetching the latest community posts..."/> : posts.length === 0 ? <Empty title="Your feed is waiting" text="Be the first person to share something with the community."/> : posts.map(post => <PostCard key={post._id} post={post} onLike={likePost} onComment={commentPost} onDelete={deletePost}/>)}</div>{pagination?.hasMore && <button className="load-more" disabled={loading} onClick={() => loadPosts(pageNo + 1, true)}>{loading ? "Loading..." : "Load more posts ↓"}</button>}</section>; }

function ExplorePage({ posts, setPage }) { const [q, setQ] = useState(""); const filtered = posts.filter(p => { const x = q.toLowerCase(); return !x || p.author?.name?.toLowerCase().includes(x) || p.author?.username?.toLowerCase().includes(x) || p.text?.toLowerCase().includes(x); }); const creators = [...new Map(posts.map(p => [p.author.username, p.author])).values()].slice(0, 6); return <section className="page-content"><div className="page-hero"><span className="eyebrow">DISCOVER</span><h1>Explore the community</h1><p>Find people, ideas and conversations worth following.</p><div className="explore-search"><span>⌕</span><input value={q} onChange={e => setQ(e.target.value)} placeholder="Search posts, names or usernames..."/></div></div><div className="explore-grid"><div><div className="page-title compact"><div><span className="eyebrow">DISCOVERED POSTS</span><h2>{q ? `Results for “${q}”` : "Trending conversations"}</h2></div></div><div className="posts">{filtered.length ? filtered.map(p => <PostCard key={p._id} post={p} onLike={() => {}} onComment={() => {}} onDelete={() => {}}/>) : <Empty icon="⌕" title="No results" text="Try a different search term."/>}</div></div><aside className="explore-side"><div className="card community-card"><span className="eyebrow">PEOPLE TO DISCOVER</span><h3>Creators in your feed</h3>{creators.length ? creators.map(c => <button className="creator-row" key={c.username} onClick={() => setPage("profile")}><Avatar username={c.username}/><span><strong>{c.name}</strong><small>@{c.username}</small></span><b>→</b></button>) : <p>No creators yet.</p>}</div><div className="card quick-card"><span className="eyebrow">COMMUNITY PULSE</span><div className="pulse-grid"><div><strong>{posts.length}</strong><span>Posts loaded</span></div><div><strong>{new Set(posts.map(p => p.author.username)).size}</strong><span>Creators</span></div><div><strong>∞</strong><span>Ideas</span></div></div></div></aside></div></section>; }

function CreatePage({ user, onCreated, setPage }) { return <section className="page-content narrow-page"><div className="page-hero"><span className="eyebrow">CREATE</span><h1>Publish something meaningful.</h1><p>Your post can be a thought, an update, a photo, or all three.</p></div><Composer user={user} onCreated={p => { onCreated(p); setPage("home"); }}/><div className="creation-tips"><div className="card tip-panel"><span>01</span><div><strong>Keep it authentic</strong><p>Share something useful, interesting or personal to your community.</p></div></div><div className="card tip-panel"><span>02</span><div><strong>Add visual context</strong><p>Upload an image when it helps tell your story.</p></div></div><div className="card tip-panel"><span>03</span><div><strong>Start a conversation</strong><p>Ask a question and invite others to join in.</p></div></div></div></section>; }

function ProfilePage({ user, posts, setPage }) { const mine = posts.filter(p => p.author?.username === user.username); return <section className="page-content"><div className="profile-hero card"><div className="profile-cover"/><div className="profile-hero-body"><Avatar username={user.username} large/><div className="profile-main"><span className="eyebrow">YOUR PROFILE</span><h1>{user.name}</h1><p>@{user.username} · {user.email}</p><div className="profile-bio">Building connections through ideas, conversations and community.</div></div><button className="ghost-btn" onClick={() => setPage("create")}>+ Create post</button></div><div className="profile-metrics"><div><strong>{mine.length}</strong><span>Posts</span></div><div><strong>{mine.reduce((a,p) => a + (p.likeCount || 0),0)}</strong><span>Likes received</span></div><div><strong>{mine.reduce((a,p) => a + (p.commentCount || 0),0)}</strong><span>Comments</span></div></div></div><div className="page-title compact"><div><span className="eyebrow">YOUR ACTIVITY</span><h2>Your posts</h2></div></div><div className="posts">{mine.length ? mine.map(p => <PostCard key={p._id} post={p} onLike={() => {}} onComment={() => {}} onDelete={() => {}}/>) : <Empty icon="◎" title="Nothing here yet" text="Create your first post to build your profile."/>}</div></section>; }

function NotificationsPage() { return <section className="page-content narrow-page"><div className="page-hero"><span className="eyebrow">ACTIVITY</span><h1>Notifications</h1><p>Stay on top of what is happening around your posts.</p></div><div className="notification-list card"><div className="notification unread"><div className="notification-icon">♥</div><div><strong>Your community is ready for your next post.</strong><p>Share an update and start a new conversation.</p><small>Just now</small></div><span/></div><div className="notification"><div className="notification-icon">◯</div><div><strong>Comments are part of the conversation.</strong><p>Check your feed to see replies and continue discussions.</p><small>Today</small></div></div><div className="notification"><div className="notification-icon">✦</div><div><strong>Welcome to Neural Social.</strong><p>Complete your profile by publishing your first update.</p><small>Today</small></div></div></div></section>; }

function App() {
  const [user, setUser] = useState(null), [booting, setBooting] = useState(true), [posts, setPosts] = useState([]), [pageNo, setPageNo] = useState(1), [pagination, setPagination] = useState(null), [loading, setLoading] = useState(false), [feedError, setFeedError] = useState(""), [page, setPage] = useState("home");
  useEffect(() => { const token = localStorage.getItem("neural_token"); if (!token) return setBooting(false); api.me().then(r => setUser(r.user)).catch(() => localStorage.removeItem("neural_token")).finally(() => setBooting(false)); }, []);
  useEffect(() => { if (user) loadPosts(1, false); }, [user]);
  async function loadPosts(target = 1, append = false) { setLoading(true); setFeedError(""); try { const r = await api.posts(target, 5); setPosts(prev => append ? [...prev, ...r.posts] : r.posts); setPagination(r.pagination); setPageNo(target); } catch (err) { if (err.status === 401) logout(); setFeedError(err.message); } finally { setLoading(false); } }
  function logout() { localStorage.removeItem("neural_token"); setUser(null); setPosts([]); setPage("home"); }
  function addPost(post) { setPosts(prev => [post, ...prev]); setPagination(prev => prev ? { ...prev, total: prev.total + 1 } : prev); }
  async function likePost(id) { try { const r = await api.toggleLike(id); setPosts(prev => prev.map(p => p._id === id ? { ...p, likeCount: r.likeCount, likedByMe: r.likedByMe } : p)); } catch (err) { if (err.status === 401) logout(); else setFeedError(err.message); } }
  async function commentPost(id, text) { const r = await api.comment(id, text); setPosts(prev => prev.map(p => p._id === id ? { ...p, commentCount: r.commentCount, comments: [...(p.comments || []), r.comment] } : p)); }
  async function deletePost(id) { if (!window.confirm("Delete this post?")) return; try { await api.deletePost(id); setPosts(prev => prev.filter(p => p._id !== id)); setPagination(prev => prev ? { ...prev, total: Math.max(0, prev.total - 1) } : prev); } catch (err) { setFeedError(err.message); } }
  if (booting) return <div className="loading-page"><div className="big-spinner"/><p>Loading Neural Social...</p></div>;
  if (!user) return <AuthScreen onAuth={setUser}/>;
  return <div className="app-shell"><Nav page={page} setPage={setPage} user={user} logout={logout}/><main className="layout"><Sidebar page={page} setPage={setPage} user={user} logout={logout}/><div className="main-stage">{page === "home" && <HomePage user={user} posts={posts} pagination={pagination} pageNo={pageNo} loading={loading} error={feedError} setError={setFeedError} addPost={addPost} likePost={likePost} commentPost={commentPost} deletePost={deletePost} loadPosts={loadPosts} setPage={setPage}/>} {page === "explore" && <ExplorePage posts={posts} setPage={setPage}/>} {page === "create" && <CreatePage user={user} onCreated={addPost} setPage={setPage}/>} {page === "notifications" && <NotificationsPage/>} {page === "profile" && <ProfilePage user={user} posts={posts} setPage={setPage}/>}</div><aside className="right-rail"><div className="card guideline-card"><span className="eyebrow">NEURAL SOCIAL</span><h3>Built for conversations.</h3><p>One place to publish, discover and interact with your community.</p><div className="feature-row"><span>♥</span> Instant likes</div><div className="feature-row"><span>◯</span> Comments stored with posts</div><div className="feature-row"><span>▧</span> Image sharing</div></div><div className="card quick-card"><span className="eyebrow">QUICK STATS</span><div className="pulse-grid"><div><strong>{posts.length}</strong><span>Loaded</span></div><div><strong>{new Set(posts.map(p => p.author?.username)).size}</strong><span>Creators</span></div><div><strong>2</strong><span>Collections</span></div></div></div></aside></main><footer className="footer">Neural Social • Full Stack Internship Round 1</footer></div>;
}
export default App;
